// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel ApplyNaturalForces
#pragma kernel MoveParticles

#include "GrowthHelpers3D.hlsl"

RWStructuredBuffer<Node3D> Nodes;

// VALUES
float deltaTime;

uint nodeCount;
uint paddedNodeCount;

float separationDistance;
float separationForce;

float attractionForce;
float laplacianSmoothing;

float nodeDrag;

StructuredBuffer<uint> NeighborIndices;
StructuredBuffer<Entry> SpatialLookup;
StructuredBuffer<uint> StartIndices;

// 
[numthreads(8, 1, 1)]
void ApplyNaturalForces(uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    
    if (id.x >= nodeCount)
        return;
    
    Node3D node = Nodes[index];

    float3 totalForce = float3(0, 0, 0);
    
    int3 currCell = PositionToCellCoord(node.position, separationDistance);
    
    // get nearby nodes within separation distance
    
    // (for now, loop over all nodes - TODO: use spatial hashing for efficiency)
    
    for (uint i = 0; i < 27; i++)
    {
        int3 offset = Offsets3D[i];
        int3 neighborCell = currCell + int3(offset.x, offset.y, offset.z);
        
        uint hash = HashCell(neighborCell.x, neighborCell.y, neighborCell.z);
        uint cellKey = KeyFromHash(hash, paddedNodeCount);
        
        uint startIndex = StartIndices[cellKey]; // get start index for this cell from precomputed start indices
        
        if (startIndex == UINT_MAX)
            continue;
        
        for (uint j = startIndex; j < paddedNodeCount; j++)
        {
            // If the cell key changes, we've exited this cell's block of particles. Stop checking.
            if (SpatialLookup[j].cellKey != cellKey)
                break;
            
            uint otherIndex = SpatialLookup[j].particleIndex;
            
            // If the other index is the same as the current node, skip to avoid self-interaction
            if (otherIndex == index)
                continue;
            
            Node3D other = Nodes[otherIndex];
            
            float3 delta = node.position - other.position;
            float distSq = dot(delta, delta);
            if (distSq > separationDistance * separationDistance)
                continue;

            float dist = sqrt(distSq);

            if (dist <= 0.0001)
                continue;

            float3 repulsionDir = delta / dist;
            float falloffFactor =
            SpikyKernelPow2(
                dist,
                separationDistance
            );

            totalForce +=
                repulsionDir *
                separationForce *
                separationDistance *
                falloffFactor;
        }
        
    }
    
    // ATTRACTION
    if (node.neighborCount > 0)
    {
        float3 neighborCenter = float3(0, 0, 0);

        for (int j = 0; j < node.neighborCount; j++)
        {
            int flatIndex = node.neighborStartIndex + j;
            uint neighborNodeIndex = NeighborIndices[flatIndex];
        
            Node3D neighbor = Nodes[neighborNodeIndex];
            

            // ATTRACTION
            float3 attractionDir = normalize(neighbor.position - node.position);
            totalForce += attractionDir * attractionForce;

            // Add to centroid for Laplacian smoothing
            neighborCenter += neighbor.position;
        }

        // LAPLACIAN SMOOTHING (move towards neighbor centroid)
        neighborCenter /= (float) node.neighborCount;
        float3 laplacianVector = neighborCenter - node.position;
        totalForce += laplacianVector * laplacianSmoothing;
    }

    totalForce += -node.velocity * nodeDrag;

    // F = m * a, so a = F / m
    node.velocity += totalForce / node.mass * deltaTime;
    
    Nodes[index] = node;
}

[numthreads(8,1,1)]
void MoveParticles (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    
    if (id.x >= nodeCount)
        return;
    
    // apply velocity
    Nodes[index].position += Nodes[index].velocity * deltaTime;
}

